global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "webhook"

receivers:
  - name: "webhook"
    webhook_configs:
      - url: "http://your_chosen_username:your_chosen_password@telegram-webhook:5000/webhook"
