global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "redpanda"
    metrics_path: "/public_metrics"
    static_configs:
      - targets:
          - "redpanda-0:9644"
          - "redpanda-1:9644"
          - "redpanda-2:9644"

rule_files:
  - "redpanda_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
